from fastapi import FastAPI, HTTPException
from typing import List
from datetime import datetime
from schemas import (
    UserCreate, UserLogin, FileUpload, Reminder,
    Preference, AIRequest, AIResponse
)

app = FastAPI()

# ----------------- User Auth -----------------

@app.post('/register')
def create_user(user: UserCreate):
    return {"message": "User created successfully"}

@app.post('/login')
def user_login(user: UserLogin):
    return {"message": "Login successful"}

# ----------------- File Upload -----------------

@app.post('/upload_file')
def upload_file(file: FileUpload):
    return {"message": "File uploaded"}

@app.get('/get_file/{file_name}')
def get_file(file_name: str):
    return {"file_name": file_name, "content": "Dummy PDF content"}

@app.get('/list_files')
def list_files():
    return {"files": []}

# ----------------- Reminders -----------------

@app.post('/set_reminder')
def set_reminder(reminder: Reminder):
    return {"message": "Reminder set"}

@app.get('/get_reminders')
def get_reminders(user_id: str):  # Optional: Add query param
    return {"reminders": []}

@app.delete('/delete_reminder/{reminder_id}')
def delete_reminder(reminder_id: int):
    return {"message": f"Reminder {reminder_id} deleted"}

# ----------------- AI Assistant -----------------

@app.post('/chat_with_ai', response_model=AIResponse)
def chat_with_ai(request: AIRequest):
    return {
        "response": "Generated reply here",
        "intent": request.intent,
        "timestamp": datetime.now()
    }

# ----------------- Preferences -----------------

@app.post('/set_preference')
def set_preference(pref: Preference):
    return {"message": "Preferences set"}

@app.put('/update_preference')
def updating_preference(pref: Preference):
    return {"message": "Preferences updated"}

@app.get('/view_preference')
def get_set_preference(user_id: str):
    return {"preferences": {}}

# ----------------- Recommendations -----------------

@app.get('/get_recommendation')
def get_recommendation(user_id: str, topic: str):
    return {"recommendations": []}

# ----------------- AI Tasks (Handled in /chat_with_ai anyway) -----------------

@app.post('/add_past_question')
def past_questions():  # May be removed or handled by AI instead
    return {"message": "Past question stored"}

@app.post('/generate_practice_question')
def generate_pre_questions():  # Same — should be handled via /chat_with_ai
    return {"question": "Generated by AI"}
